# Generated by Django 4.1.5 on 2024-06-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_productone_tags_imagess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('email', models.CharField(max_length=155)),
                ('subject', models.CharField(max_length=155)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='imagess',
            name='image',
            field=models.ImageField(default='', upload_to='shop/imagess'),
        ),
    ]
