# Generated by Django 3.2.25 on 2024-07-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_checkout_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
