# Generated by Django 3.2.25 on 2024-07-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20240717_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='first_name',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='last_name',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
