# Generated by Django 3.2.25 on 2024-07-25 06:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_commingsoon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoptwocolum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('image', models.ImageField(default='', upload_to='shop/imagessss')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('New', 'New'), ('Old', 'Old')], max_length=200)),
                ('information', models.TextField()),
                ('description', models.TextField()),
                ('stock', models.CharField(choices=[('IN STOCK', 'IN STOCK'), ('OUT OF STOCK', 'OUT OF STOCK')], max_length=200)),
                ('status', models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], max_length=200)),
                ('created_date', models.CharField(default=django.utils.timezone.now, max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.brand')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categories')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.color')),
                ('filter_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.filter_price')),
            ],
        ),
        migrations.AlterField(
            model_name='imagess',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.CreateModel(
            name='Tagsss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shopcolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.shoptwocolum')),
            ],
        ),
        migrations.CreateModel(
            name='Imagessss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='shop/imagessss')),
                ('shopcolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.shoptwocolum')),
            ],
        ),
    ]
